workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - changelog
  - build
  - test
  - security
  - publish
  - kmmPublish

variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  KONAN_DATA_DIR: $CI_PROJECT_DIR/.konan
  KOTLIN_DATA_DIR: $CI_PROJECT_DIR/.kotlin
  BUILD_LINUX_IMAGE_NAME: registry.gitlab.com/trixnity/kmp-dockerfiles/kmp-dockerfiles-base:latest
  BUILD_LINUX_IMAGE_NAME_EMULATOR: registry.gitlab.com/trixnity/kmp-dockerfiles/kmp-dockerfiles-emulator:latest

.cache-linux: &cache-linux
  - key: global-trixnity-messenger-cache-linux
    policy: pull-push
    paths:
      - $GRADLE_USER_HOME
      - $KONAN_DATA_DIR
  - key: "$CI_COMMIT_REF_NAME-linux"
    policy: push
    paths:
      - $GRADLE_USER_HOME
      - $KONAN_DATA_DIR
      - $KOTLIN_DATA_DIR

.pull-cache-linux: &pull-cache-linux
  - key: "$CI_COMMIT_REF_NAME-linux"
    fallback_keys: [ "global-trixnity-messenger-cache-linux" ]
    policy: pull
    paths:
      - $GRADLE_USER_HOME
      - $KONAN_DATA_DIR
      - $KOTLIN_DATA_DIR

.cache-mac: &cache-mac
  - key: global-trixnity-messenger-cache-mac
    policy: pull-push
    paths:
      - $GRADLE_USER_HOME
      - $KONAN_DATA_DIR
      - $KOTLIN_DATA_DIR
  - key: "$CI_COMMIT_REF_NAME-mac"
    policy: push
    paths:
      - $GRADLE_USER_HOME
      - $KONAN_DATA_DIR
      - $KOTLIN_DATA_DIR

.pull-cache-mac: &pull-cache-mac
  - key: "$CI_COMMIT_REF_NAME-mac"
    fallback_keys: [ "global-trixnity-messenger-cache-mac" ]
    policy: pull
    paths:
      - $GRADLE_USER_HOME
      - $KONAN_DATA_DIR
      - $KOTLIN_DATA_DIR

.artifact-reports: &artifact-reports
  name: reports
  when: always
  paths: [ "**/build/reports" ]
  reports:
    junit: "**/build/test-results/**/TEST-*.xml"

.docker-variables: &docker-variables
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"

.if-merge-request: &if-merge-request
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

.if-merge-request-or-main: &if-merge-request-or-main
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

.if-not-scheduled: &if-not-scheduled
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never

.if-main: &if-main
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.if-release: &if-release
  - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+.*/'

.if-kmm-publish: &if-kmm-publish
  - if: $CI_PIPELINE_SOURCE == "schedule" && $KMM_PUBLISH == "true"

build:mac:
  stage: build
  interruptible: true
  tags: [ "connect2x-mac" ]
  cache:
    - *cache-mac
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      compileKotlin{IosArm64,IosSimulatorArm64,IosX64}
      compileTestKotlin{IosSimulatorArm64,IosX64}
      linkDebugTestIosX64
      --stacktrace

build:linux:
  stage: build
  interruptible: true
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  cache:
    - *cache-linux
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      compileKotlin{Jvm,Js}
      compileReleaseKotlinAndroid
      compileTestKotlin{Jvm,Js}
      compileReleaseUnitTestKotlinAndroid
      --stacktrace

test:mac:
  stage: test
  interruptible: true
  timeout: 1h
  needs: [ "build:mac" ]
  tags: [ "connect2x-mac" ]
  cache:
    - *pull-cache-mac
  artifacts: *artifact-reports
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      {iosSimulatorArm64,iosX64}Test
      --stacktrace

test:linux:
  stage: test
  interruptible: true
  timeout: 1h
  needs: [ "build:linux" ]
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  cache:
    - *pull-cache-linux
  artifacts: *artifact-reports
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      {jvm,js}Test -x :integrationtests:jvmTest
      --stacktrace

test:smoketest-desktop-linux:
  stage: test
  interruptible: true
  timeout: 1h
  needs: [ "build:linux" ]
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  cache:
    - *pull-cache-linux
  artifacts: *artifact-reports
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      :trixnity-messenger-compose-view:desktopTest
      --stacktrace

test:smoketest-web-linux:
  stage: test
  interruptible: true
  timeout: 1h
  needs: [ "build:linux" ]
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  cache:
    - *pull-cache-linux
  artifacts: *artifact-reports
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      :trixnity-messenger-compose-view:webBrowserFirefoxTest
      --stacktrace

test:smoketest-android-linux:
  stage: test
  interruptible: true
  timeout: 15m
  needs: [ "build:linux" ]
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME_EMULATOR
  cache:
    - *pull-cache-linux
  artifacts:
    paths:
      - emulator.log
  rules:
    - *if-merge-request-or-main
  script:
    - ./scripts/start_emulator.sh
    - ./gradlew :trixnity-messenger-compose-view:connectedAndroidTest --stacktrace

test:integration-test:
  stage: test
  interruptible: true
  timeout: 30m
  needs: [ "build:linux" ]
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  services:
    - name: docker:dind
  cache:
    - *pull-cache-linux
  variables: *docker-variables
  artifacts: *artifact-reports
  rules:
    - *if-merge-request-or-main
  script:
    - ./gradlew
      :integrationtests:jvmTest
      --stacktrace

security:dependencies:
  stage: security
  interruptible: true
  timeout: 30m
  needs: [ ]
  tags: [ "saas-linux-small-amd64" ]
  image:
    name: "aquasec/trivy"
    entrypoint: [ "" ]
  variables:
    TRIVY_CACHE_DIR: ".trivycache/"
    WITH_LOCK: true
  cache:
    paths:
      - .trivycache/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+.*/'
      allow_failure: false
    - if: $CI_PIPELINE_SOURCE == "schedule"
      allow_failure: false
  artifacts:
    when: always
    reports:
      dependency_scanning: report.json
  before_script:
    - apk add openjdk17
    - ./gradlew dependenciesForAll --write-locks --no-parallel > dependencies.txt
  script:
    - trivy repo ./ --exit-code 0
    - trivy repo ./ --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output report.json
    - trivy repo ./ --exit-code 1 --severity CRITICAL

changelog:
  stage: changelog
  interruptible: true
  timeout: 5m
  tags: [ "saas-linux-small-amd64" ]
  rules:
    - *if-merge-request
  script:
    - git fetch origin main
    - |
      if git diff --name-only HEAD origin/main | grep "CHANGELOG.md"; then
        echo "CHANGELOG.md has changed"
      else
        echo "CHANGELOG.md has not changed"
        exit 1
      fi

publish:mac:
  stage: publish
  tags: [ "connect2x-mac" ]
  cache:
    - *cache-mac # is reused by kmmPublish:mac
  rules:
    - *if-kmm-publish
    - *if-not-scheduled
    - *if-main
    - *if-release
  script:
    - ./gradlew
      publish{IosArm64,IosSimulatorArm64,IosX64}PublicationToGitlabRepository
      --stacktrace

publish:linux:
  stage: publish
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  cache:
    - *pull-cache-linux
  rules:
    - *if-not-scheduled
    - *if-main
    - *if-release
  script:
    - ./gradlew
      publish{KotlinMultiplatform,Jvm,Js,AndroidRelease,Desktop,Web}PublicationToGitlabRepository
      --stacktrace

kmmPublish:mac:
  stage: kmmPublish
  tags: [ "connect2x-mac" ]
  cache:
    - *pull-cache-mac
  rules:
    - *if-kmm-publish
    - *if-release
  timeout: 2h
  needs: [ "publish:mac" ]
  script:
    - ./kmmPublish.sh
