workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - changelog
  - build
  - test
  - security
  - publish
  - kmmPublish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx1g -Dorg.gradle.configureondemand=true -Djava.security.egd=file:/dev/./urandom -Djava.net.preferIPv4Stack=true"
  BUILD_LINUX_IMAGE_NAME: registry.gitlab.com/connect2x/build-infrastructure/kmp-dockerfiles/kmp-dockerfiles-base:latest
  BUILD_LINUX_IMAGE_NAME_EMULATOR: registry.gitlab.com/connect2x/build-infrastructure/kmp-dockerfiles/kmp-dockerfiles-emulator:latest
  BUILD_LINUX_IMAGE_NAME_TRIVY: registry.gitlab.com/connect2x/build-infrastructure/kmp-dockerfiles/kmp-dockerfiles-trivy:latest
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    command: [ "--tls=false" ]

.artifact-reports: &artifact-reports
  name: reports
  when: always
  paths: [ "**/build/reports", "**/build/**/yarn.lock", "**/build/kotlin/abi-legacy" ]
  reports:
    junit: "**/build/test-results/**/TEST-*.xml"
    coverage_report:
      coverage_format: jacoco
      path: trixnity-messenger/build/reports/kover/reportJvm.xml

.docker-variables: &docker-variables
  DIST_JAVA_HOME: /lib/jvm/temurin-24-jdk-amd64
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"

.if-merge-request: &if-merge-request
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

.if-release: &if-release
  - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+.*/'

.if-dev-release: &if-dev-release
  - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+.*/'
    when: never
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: '$CI_COMMIT_BRANCH =~ /^v-\d+.\d+.\d+.*/'

build:mac:
  stage: build
  interruptible: true
  tags: [ "connect2x-mac" ]
  rules:
    - *if-merge-request
  script:
    - ./gradlew
      compileKotlin{IosArm64,IosSimulatorArm64,IosX64}
      compileTestKotlin{IosSimulatorArm64,IosX64}
      --stacktrace

build:linux:
  stage: build
  interruptible: true
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  rules:
    - *if-merge-request
  script:
    - gradle
      compileKotlin{Jvm,Js,WasmJs}
      compileReleaseKotlinAndroid
      :trixnity-messenger-compose-app:assembleRelease
      compileTestKotlin{Jvm,Js,WasmJs}
      compileReleaseUnitTestKotlinAndroid
      --stacktrace
  artifacts:
    paths:
      - trixnity-messenger-compose-app/build/outputs/apk/release/trixnity-messenger-compose-app-release.apk
    expire_in: 1 day
    expose_as: 'Android App APK'

test:mac:
  stage: test
  interruptible: true
  timeout: 1h
  needs:
    - job: "build:mac"
      artifacts: false
  tags: [ "connect2x-mac" ]
  artifacts: *artifact-reports
  rules:
    - *if-merge-request
  script:
    - ./gradlew
      :trixnity-messenger:{iosSimulatorArm64,iosX64}Test
      --stacktrace

test:linux:
  stage: test
  interruptible: true
  timeout: 1h
  needs:
    - job: "build:linux"
      artifacts: false
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  artifacts: *artifact-reports
  rules:
    - *if-merge-request
  script:
    - gradle
      :trixnity-messenger:{jvm,js,wasmJs}Test
      :trixnity-messenger:testCoverage
      --stacktrace
  coverage: '/Total test coverage.+ ([0-9]{1,3}%)/'

test:smoketest-jvm:
  stage: test
  interruptible: true
  timeout: 1h
  needs:
    - job: "build:linux"
      artifacts: false
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME_EMULATOR
  artifacts:
    when: always
    paths: [ "**/screenshots", "**/build/reports" ]
  rules:
    - *if-merge-request
  script:
    - /start-emulator.sh
    - bash -c "socat TCP-LISTEN:8008,fork TCP:docker:8008 &"
    - bash -c "adb logcat | grep System.out > logcat.txt &"
    - gradle --profile
      :trixnity-messenger-compose-view:{connectedAndroid,jvm}Test
      --stacktrace
  after_script:
    - bash -c "cat logcat.txt"

test:smoketest-js:
  stage: test
  interruptible: true
  timeout: 1h
  needs:
    - job: "build:linux"
      artifacts: false
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  artifacts:
    when: always
    paths: [ "**/screenshots", "**/build/reports" ]
  rules:
    - *if-merge-request
  script:
    - bash -c "socat TCP-LISTEN:8008,fork TCP:docker:8008 &"
    - gradle 
      :trixnity-messenger-compose-view:{jsBrowser,wasmJsBrowser}Test
      --stacktrace

# TODO cannot be run on virtualized macOS
#test:smoketest-ios:
#  stage: test
#  interruptible: true
#  timeout: 1h
#  needs: [ "build:mac" ]
#  tags: [ "connect2x-mac" ]
#  artifacts:
#    when: always
#    paths: [ "screenshots", "**/build/reports" ]
#    reports:
#      coverage_report:
#        coverage_format: jacoco
#        path: trixnity-messenger/build/reports/kover/reportJvm.xml
#  rules:
#    - *if-merge-request
#  script:
#    - ./scripts/start_simulator.sh
#    - ./gradlew
#      :trixnity-messenger-compose-view:iosX64Test
#      :trixnity-messenger-compose-view:testCoverage
#      --stacktrace
#  coverage: '/Total test coverage.+ ([0-9]{1,3}%)/'

test:integration-test:
  stage: test
  interruptible: true
  timeout: 30m
  needs:
    - job: "build:linux"
      artifacts: false
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  services:
    - name: docker:dind
  variables: *docker-variables
  artifacts: *artifact-reports
  rules:
    - *if-merge-request
  script:
    - gradle
      :integrationtests:jvmTest
      --stacktrace

# requires macOS since it can build/emulate all other targets
checkAbi:
  stage: test
  interruptible: true
  timeout: 1h
  needs:
    - job: "build:mac"
      artifacts: false
  tags: [ "connect2x-mac" ]
  artifacts: *artifact-reports
  rules:
    - *if-merge-request
  script:
    - ./gradlew dumpLegacyAbi --stacktrace
    - ./gradlew checkLegacyAbi --stacktrace

security:dependencies:
  stage: security
  interruptible: true
  timeout: 30m
  needs: [ ]
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME_TRIVY
  variables:
    TRIVY_CACHE_DIR: ".trivycache/"
    WITH_LOCK: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+.*/'
      allow_failure: false
    - if: $CI_PIPELINE_SOURCE == "schedule"
      allow_failure: false
  artifacts:
    when: always
    reports:
      dependency_scanning: report.json
  script:
    - gradle dependenciesForAll --write-locks > dependencies.txt
    - trivy repo ./ --exit-code 0
    - trivy repo ./ --exit-code 0 --format template --template "@/usr/local/share/trivy/templates/gitlab.tpl" --output report.json
    - trivy repo ./ --exit-code 1 --severity CRITICAL

changelog:
  stage: changelog
  interruptible: true
  timeout: 5m
  tags: [ "saas-linux-small-amd64" ]
  rules:
    - *if-merge-request
  script:
    - git fetch origin main
    - |
      if git diff --name-only HEAD origin/main | grep "CHANGELOG.md"; then
        echo "CHANGELOG.md has changed"
      else
        echo "CHANGELOG.md has not changed"
        exit 1
      fi

publish:mac-dev:
  stage: publish
  tags: [ "connect2x-mac" ]
  rules:
    - *if-dev-release
  script:
    - ./gradlew
      publish{IosArm64,IosSimulatorArm64,IosX64}PublicationToGitlabRepository
      --stacktrace

publish:linux-dev:
  stage: publish
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  rules:
    - *if-dev-release
  variables:
    DIST_JAVA_HOME: /lib/jvm/temurin-24-jdk-amd64
  script:
    - gradle
      publish{KotlinMultiplatform,Jvm,Js,WasmJs,AndroidRelease}PublicationToGitlabRepository
      --stacktrace

publish:release:
  stage: publish
  tags: [ "connect2x-mac" ]
  timeout: 2h
  rules:
    - *if-release
  script:
    - ./gradlew
      publishAllPublicationsToGitLabRepository
      publishAndReleaseToMavenCentral
      --stacktrace

staging:web:
  stage: publish
  tags: [ "connect2x-linux" ]
  image: $BUILD_LINUX_IMAGE_NAME
  rules:
    - *if-merge-request
  needs: [ "build:linux" ]
  artifacts:
    name: web
    when: always
    paths:
      - public
    expire_in: 7d
  variables:
    DIST_JAVA_HOME: /lib/jvm/temurin-24-jdk-amd64
  script:
    - gradle
      :trixnity-messenger-compose-app:jsBrowserDistribution
      --stacktrace
    - mv trixnity-messenger-compose-app/build/dist/js/productionExecutable public
  environment:
    name: review/${CI_MERGE_REQUEST_IID}
    url: https://connect2x.gitlab.io/-/trixnity-messenger/trixnity-messenger/-/jobs/${CI_JOB_ID}/artifacts/public/index.html

kmmPublish:mac:
  stage: kmmPublish
  tags: [ "connect2x-mac" ]
  rules:
    - *if-release
  timeout: 2h
  needs: [ "publish:release" ]
  script:
    - ./kmmPublish.sh
