services:
  synapse:
    # https://github.com/element-hq/synapse/releases
    image: "matrixdotorg/synapse:v1.138.0"
    container_name: "trixnity-messenger-uitest-synapse-${GRADLE_TEST_SYNAPSE_PORT}"
    volumes:
      - "./data/homeserver.yaml:/data/homeserver.yaml:ro"
      - "./data/localhost.log.config:/data/localhost.log.config:ro"
      - "./data/localhost.signing.key:/data/localhost.signing.key:ro"
    tmpfs:
      - /data
    environment:
      VIRTUAL_HOST: "localhost"
      VIRTUAL_PORT: 8008
      SYNAPSE_SERVER_NAME: "localhost"
      SYNAPSE_REPORT_STATS: "no"
      UID: "0"
      GID: "0"
    ports:
      - ${GRADLE_TEST_SYNAPSE_PORT}:8008
